# Generated by Django 4.2.7 on 2025-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors_app', '0002_tailorprofile_store_picture_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoringrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by customer for cancellation', null=True),
        ),
    ]
