# Generated by Django 4.2.7 on 2025-10-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailors_app', '0003_tailoringrequest_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoringrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the request was deleted', null=True),
        ),
        migrations.AddField(
            model_name='tailoringrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tailoringrequest',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion', null=True),
        ),
        migrations.AddField(
            model_name='tailoringrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
